### ISSUE TITLE
Crash Volume Desktop

### ISSUE THREAD

**Issue by MatthieuLamp** [miyako/4d-plugin-ical-v4#2]
Hello,

since installing the iCal plugin, I've had a lot of random crashes with 4D Volume Desktop.
For example, I open the app, create an appointment, want to change the data file with the OPEN DATA FILE command, and 4D Volume Desktop crashes. 

If I remove the plugin, I don't get any more crashes.
Is this due to the "$CALENDAR" process?

I've attached an error message.
Thanks for your help.
4D 20R5, macOS 14.6.1
[Erreur.pdf](https://github.com/user-attachments/files/16595976/Erreur.pdf)

**Comment by miyako** [comment]
the plugin sets up the notification process at startup and closes it during $xx (On Exit). but it needs time to cleanup. OPEN DAT FILE, OPEN DATABASE, RESTART 4D are very powerful commands. it may not work well with the notification model.

**Comment by miyako** [comment]
with Volume Desktop, there is also the sponsored message window.

* does the application crash if you run compiled, but don't build the application?
* do you even need the notification feature?

**Comment by miyako** [comment]
in other words, maybe you should use v3, not v4.

**Comment by MatthieuLamp** [comment]
> with Volume Desktop, there is also the sponsored message window.
> 
> * does the application crash if you run compiled, but don't build the application?
> * do you even need the notification feature?

I don't have a problem with 4D, only with 4D Volume Desktop
But because I don't have NSCalendarsUsageDescription rights with 4D

Is it possible to disable the Notification Process? Because for me it's not useful

**Comment by MatthieuLamp** [comment]
> in other words, maybe you should use v3, not v4.

I've just tried v3
but I can't create the event...

**Comment by miyako** [comment]
the plugin was developed for a customer who is using it with Volume Desktop and they also use OPEN DATA FILE, 

but they are OEM which means they don't get the sponsored message. maybe that's the difference. by the way, do you have code in On Exit?

**Comment by MatthieuLamp** [comment]
> the plugin was developed for a customer who is using it with Volume Desktop and they also use OPEN DATA FILE,
> 
> but they are OEM which means they don't get the sponsored message. maybe that's the difference. by the way, do you have code in On Exit?

I actually have the sponsored post
and yes I have code at closing time

**Comment by miyako** [comment]
> but I can't create the event...

do you mean you get an error?

**Comment by MatthieuLamp** [comment]
> > but I can't create the event...
> 
> do you mean you get an error?

No

**Comment by MatthieuLamp** [comment]
why not have a command that disables notifications?

**Comment by MatthieuLamp** [comment]
> in other words, maybe you should use v3, not v4.

this code provided in the v3 project does not work
```
$status:=iCal Request permisson

Si ($status.success)
	
	$options:=Créer objet
	$options.calendar:=Créer objet("title"; "TEST")
	$options.title:="TEST EVENT"
	$options.startDate:=Date du jour
	$options.endDate:=Date du jour+1
	$options.isAllDay:=Vrai
	
	$options.recurrenceRule:=Créer objet
	$options.recurrenceRule.recurrenceType:=0  //Daily
	$options.recurrenceRule.recurrenceInterval:=1  //every day
	$options.recurrenceRule.recurrenceEnd:=Créer objet
	$options.recurrenceRule.recurrenceEnd.occurrenceCount:=3
	
	$status:=iCal Create event($options)
	
	Si ($status.success)
		$status:=iCal Get event property($status.event)
		
	Fin de si 
	
Fin de si 
```

**Comment by miyako** [comment]
I see, `iCal Get default calendar` is not working.

**Comment by miyako** [comment]
it is a bit tricky to allow casual enable/disable of the listener process. 

I have added `iCal KILL WORKER` in [4.2.0](https://github.com/miyako/4d-plugin-ical-v4/releases/tag/4.2.0)

it is basically preëmpting what is supposed to be done internally at On Exit.

**Comment by MatthieuLamp** [comment]
> it is a bit tricky to allow casual enable/disable of the listener process.
> 
> I have added `iCal KILL WORKER` in [4.2.0](https://github.com/miyako/4d-plugin-ical-v4/releases/tag/4.2.0)
> 
> it is basically preëmpting what is supposed to be done internally at On Exit.

Thank you. I'll give it a try. 
What parameter should I enter for this new command?

**Comment by miyako** [comment]
no parameters.

**Comment by MatthieuLamp** [comment]
> it is a bit tricky to allow casual enable/disable of the listener process.
> 
> I have added `iCal KILL WORKER` in [4.2.0](https://github.com/miyako/4d-plugin-ical-v4/releases/tag/4.2.0)
> 
> it is basically preëmpting what is supposed to be done internally at On Exit.

it seems to crash a little less
but it's not fixed

thanks for your help

**Comment by miyako** [comment]
how are you using the command?

On Startup would be too early and On Exit would be too late. 

it should be somewhere in the middle.

**Comment by MatthieuLamp** [comment]
> how are you using the command?
> 
> On Startup would be too early and On Exit would be too late.
> 
> it should be somewhere in the middle.

I tested
on opening
on closing
on middle
the app always crashes

**Comment by miyako** [comment]
maybe the cleanup needs to be done in the main process. this is internal to the plugin. I will post an update later.

**Comment by MatthieuLamp** [comment]
> maybe the cleanup needs to be done in the main process. this is internal to the plugin. I will post an update later.

if ical-v3 works, I use this version
because I don't need v4 notifications

thank you for your help and your time

**Comment by miyako** [comment]
https://github.com/miyako/4d-plugin-ical-v4/releases/tag/4.3.0

**Comment by MatthieuLamp** [comment]
> https://github.com/miyako/4d-plugin-ical-v4/releases/tag/4.3.0

not yet
never mind, I'll use v3
thanks a lot
